name: CI

on:
  push:
  pull_request:

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train (if needed)
        run: |
          python - <<'PY'
          import pathlib
          if not pathlib.Path("models/model.joblib").exists():
              import train
              train.train_and_save()
          print("Modelo OK")
          PY

      - name: Run unit tests
        run: pytest -q

      - name: Build docker image
        run: docker build -t mlops-bc:ci .

      - name: Run container
        run: docker run -d --name mlops-bc -p 8000:8000 mlops-bc:ci

      - name: Wait for API
        run: |
          for i in {1..30}; do
            curl -sSf http://127.0.0.1:8000/ && break
            sleep 1
          done

      - name: Smoke test /predict
        run: |
          curl -s -X POST http://127.0.0.1:8000/predict \
            -H "Content-Type: application/json" \
            -d "{\"features\": [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}" | tee /dev/stderr
          
      - name: Stop container
        if: always()
        run: docker rm -f mlops-bc
